import "~/styles/globals.css";
import { SessionProvider } from "next-auth/react";
import { GeistSans } from "geist/font/sans";
import { TRPCReactProvider } from "~/trpc/react";
import PageLayout from "./_components/PageLayout";
import { CartProvider } from "./_context/cart-context";
import { HydrateClient } from "~/trpc/server";
import { SigninLink } from './_components/signlink';
import { auth } from "~/server/auth";

export const metadata = {
  title: "Food Delivery Service",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logo.svg" }],
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth();

  if (!session) {
    return (
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <TRPCReactProvider>
            <SessionProvider>
              <SigninLink />
            </SessionProvider>
          </TRPCReactProvider>
        </body>
      </html>
    );
  }

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <SessionProvider>
            <HydrateClient>
              <CartProvider>
                <PageLayout>
                  {children}
                </PageLayout>
              </CartProvider>
            </HydrateClient>
          </SessionProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
